platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

target 'TicTacToe' do
  pod 'RIBs'
  pod 'SnapKit'
  pod 'RxCocoa'
  pod 'RIBsTreeViewer', :git => "https://github.com/srea/RIBsTreeViewerClient.git", :branch => "feature/demo"
end
